<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title>{{ $title ?? 'Laravel' }}</title>

<link rel="preconnect" href="https://fonts.bunny.net">
<link href="https://fonts.bunny.net/css?family=instrument-sans:400,500,600" rel="stylesheet" />
<script src="https://cdn.tailwindcss.com"></script>
<script id="tailwind-config">tailwind.config={theme:{extend:{"colors":{"on-primary-fixed":"#001946","tertiary-container":"#8b2e01","surface-container-high":"#dce9ff","tertiary-fixed":"#ffdbcf","primary-fixed":"#dae2ff","outline-variant":"#c3c6d5","on-tertiary-fixed-variant":"#802900","on-background":"#0b1c30","surface-container-highest":"#d3e4fe","surface-container-low":"#eff4ff","surface-tint":"#2559bd","on-tertiary":"#ffffff","on-surface-variant":"#434653","on-secondary-container":"#fefcff","inverse-surface":"#213145","on-surface":"#0b1c30","secondary-fixed":"#d7e2ff","on-error":"#ffffff","secondary-fixed-dim":"#abc7ff","primary-container":"#0047ab","on-primary-fixed-variant":"#00419e","surface-container-lowest":"#ffffff","surface-bright":"#f8f9ff","on-secondary-fixed-variant":"#004590","tertiary-fixed-dim":"#ffb59a","surface-dim":"#cbdbf5","on-error-container":"#93000a","surface":"#f8f9ff","inverse-primary":"#b1c5ff","tertiary":"#651f00","on-tertiary-fixed":"#380d00","background":"#f8f9ff","on-primary-container":"#a5bdff","surface-variant":"#d3e4fe","outline":"#737784","surface-container":"#e5eeff","error":"#ba1a1a","secondary-container":"#0072e5","primary":"#00327d","secondary":"#005ab7","error-container":"#ffdad6","on-tertiary-container":"#ffaa8a","on-secondary":"#ffffff","inverse-on-surface":"#eaf1ff","primary-fixed-dim":"#b1c5ff","on-primary":"#ffffff","on-secondary-fixed":"#001b3f"},"borderRadius":{"DEFAULT":"0.125rem","lg":"0.25rem","xl":"0.5rem","full":"0.75rem"},"spacing":{"md":"16px","xs":"4px","lg":"24px","gutter":"24px","sm":"8px","margin":"32px","xl":"32px","base":"4px"},"fontFamily":{"headline-lg":["Inter"],"label-md":["Inter"],"body-sm":["Inter"],"body-md":["Inter"],"headline-md":["Inter"],"body-lg":["Inter"],"display":["Inter"],"mono-md":["monospace"]},"fontSize":{"headline-lg":["28px",{"lineHeight":"36px","letterSpacing":"-0.01em","fontWeight":"600"}],"label-md":["12px",{"lineHeight":"16px","letterSpacing":"0.05em","fontWeight":"600"}],"body-sm":["12px",{"lineHeight":"18px","fontWeight":"400"}],"body-md":["14px",{"lineHeight":"20px","fontWeight":"400"}],"headline-md":["20px",{"lineHeight":"28px","fontWeight":"600"}],"body-lg":["16px",{"lineHeight":"24px","fontWeight":"400"}],"display":["36px",{"lineHeight":"44px","letterSpacing":"-0.02em","fontWeight":"700"}],"mono-md":["14px",{"lineHeight":"20px","fontWeight":"400"}]}}}}</script><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet"/>

@vite(['resources/css/app.css', 'resources/js/app.js'])
@fluxAppearance
